version: '3.8'

services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workspace:/root/workspace
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: sh
